import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const eventLog = [
    "2026-04-28 09:12 UTC - PRJ-NEXUS ingestion started by Associate A.",
    "2026-04-28 09:16 UTC - KPI extraction completed, 4 metrics persisted.",
    "2026-04-28 09:17 UTC - Risk flag CUSTOMER_CONCENTRATION raised.",
    "2026-04-28 09:24 UTC - IC one-pager draft v0.3 generated by Otto."
];
const evidenceBundles = [
    { id: "IC-742", hash: "sha256:3df9b7a89f4b12f6...", items: "CIM, KPI extraction, risk rationale, memo draft" },
    { id: "IC-739", hash: "sha256:ee1c7b30a0cd5581...", items: "Financials, diligence checklist, voting notes" },
    { id: "AUD-113", hash: "sha256:5a9fd1d1490ecf72...", items: "LP commentary, fund KPI snapshot, disclosures" }
];
export function AuditVaultPage() {
    return (_jsxs("section", { className: "page", children: [_jsx("h2", { children: "Audit Vault" }), _jsx("p", { className: "muted", children: "Global infrastructure layer for immutable event logs and evidence bundles." }), _jsxs("article", { className: "card module-card", children: [_jsx("h3", { children: "Event Log" }), _jsx("ul", { className: "module-list", children: eventLog.map((item) => (_jsx("li", { children: item }, item))) })] }), _jsxs("article", { className: "card module-card", children: [_jsx("h3", { children: "Evidence Bundles" }), _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Bundle" }), _jsx("th", { children: "SHA-256 Hash" }), _jsx("th", { children: "Contents" })] }) }), _jsx("tbody", { children: evidenceBundles.map((bundle) => (_jsxs("tr", { children: [_jsx("td", { children: bundle.id }), _jsx("td", { children: bundle.hash }), _jsx("td", { children: bundle.items })] }, bundle.id))) })] })] })] }));
}
