const eventLog = [
  "2026-04-28 09:12 UTC - PRJ-NEXUS ingestion started by Associate A.",
  "2026-04-28 09:16 UTC - KPI extraction completed, 4 metrics persisted.",
  "2026-04-28 09:17 UTC - Risk flag CUSTOMER_CONCENTRATION raised.",
  "2026-04-28 09:24 UTC - IC one-pager draft v0.3 generated by Otto."
];

const evidenceBundles = [
  { id: "IC-742", hash: "sha256:3df9b7a89f4b12f6...", items: "CIM, KPI extraction, risk rationale, memo draft" },
  { id: "IC-739", hash: "sha256:ee1c7b30a0cd5581...", items: "Financials, diligence checklist, voting notes" },
  { id: "AUD-113", hash: "sha256:5a9fd1d1490ecf72...", items: "LP commentary, fund KPI snapshot, disclosures" }
];

export function AuditVaultPage() {
  return (
    <section className="page">
      <h2>Audit Vault</h2>
      <p className="muted">Global infrastructure layer for immutable event logs and evidence bundles.</p>

      <article className="card module-card">
        <h3>Event Log</h3>
        <ul className="module-list">
          {eventLog.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      </article>

      <article className="card module-card">
        <h3>Evidence Bundles</h3>
        <table>
          <thead>
            <tr>
              <th>Bundle</th>
              <th>SHA-256 Hash</th>
              <th>Contents</th>
            </tr>
          </thead>
          <tbody>
            {evidenceBundles.map((bundle) => (
              <tr key={bundle.id}>
                <td>{bundle.id}</td>
                <td>{bundle.hash}</td>
                <td>{bundle.items}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </article>
    </section>
  );
}
